// apps/property-explorer/src/workbench/Workbench.tsx
//
// PE WORKBENCH CHASSIS (WB1) — the top-right BUBBLE RAIL + the ONE shared
// dock every tool opens into.
//
// CHROME v2 (2026-08-27). The rail and the dock were restyled to the Smart Site
// chrome v2 drop: 34px bubbles with real states, a 36px dock header carrying a
// blue glyph and an uppercase title, one 340 dock width, radius 10, the v2
// hairline set, and the one panel motion (own height + 3% scale from the
// anchored corner, never a slide from off-screen).
//
// WHAT DID NOT CHANGE, by operator ruling 2026-08-27: the drop's SPEC section 2
// asked for multi-dock stacking with fold-to-header in a LEFT column. That was
// declined. ONE tool open at a time and the right-hand dock stay the law, and
// the guard tests in workbench.test.tsx that stop multi-open returning stay
// armed. This file is a restyle; nextOpenToolId is still the only rule.
//
// THE DESIGN LAW (non-negotiable): the clean map-first PE stays the star; the
// cluster is the ONLY always-on element; every capability opens into this ONE
// dock (top-right, natural height); ONE tool open at a time — opening a bubble
// REPLACES the dock content; tapping the active bubble (or the dock's ×)
// closes the dock. Never two workbench docks, never a split screen. Tool state
// persists PER-PROPERTY across open/close via useDockToolState.
//
// PLACEMENT: the cluster hugs the top-right edge; the dock opens to its LEFT
// in the brief's original space (still a RIGHT-rail dock). Left map utilities
// (notifications, legend, draw, layers) are a separate system in MapToolset
// and may stack. Workbench tools never stack on the left.
//
// LATER WAVES: add tools in registry.tsx through the WorkbenchToolDef contract
// (types.ts). Do NOT edit this file to add a tool.

import { useEffect, useMemo, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import {
  dockLayoutStyle as resolveDockLayoutStyle,
  mobileToolPickerStyle,
  workbenchClusterStyle,
} from "../browse/mobile-layout";
import { useMobilePanel } from "../browse/MobilePanelContext";
import type { WorkbenchHostActions, WorkbenchToolDef } from "./types";

import { WorkbenchProvider } from "./WorkbenchContext";
import type { WorkbenchToolStateStore } from "./tool-state-store";
import { BubbleTip } from "../components/BubbleTip";
import { PE, MOTION } from "../styles/pe-chrome";
import {
  closeOneDock,
  expandDock,
  pruneStack,
  syncStack,
  tapDock,
  EMPTY_STACK,
  type DockStack,
} from "./dock-stack";
import { StateNote } from "../components/StateNote";


/**
 * Dock single-tenancy, as a pure rule: tapping the active bubble closes the
 * dock; tapping any other bubble REPLACES the dock content with that tool.
 */
export function nextOpenToolId(
  current: string | null,
  tapped: string,
): string | null {
  return current === tapped ? null : tapped;
}

/**
 * Left map-utility stack only (draw / layers / notifications). Workbench
 * tools must use nextOpenToolId — never this.
 */
export function nextOpenToolIds(current: string[], tapped: string): string[] {
  return current.includes(tapped)
    ? current.filter((id) => id !== tapped)
    : [...current, tapped];
}

/** Workbench docks on the right. Left stacking is MapToolset, not this chassis. */
export const DEFAULT_DOCK_SIDE = "right" as const;

/**
 * Dock POSITION/SIZE, as a pure rule (Fix A — expand-to-floating-box):
 *   COMPACT (default): hugs the top-right in the brief's original space
 *     (min 400px wide, viewport-height-capped).
 *   EXPANDED: a large floating box offset from the right edge with generous
 *     margins so the main map stays visible AROUND it — never full-screen —
 *     so a cramped report (the flood study map + legend especially) reads
 *     clearly. Extracted so the layout rule is unit-testable without a click
 *     harness (the file's `nextOpenToolId` pure-rule precedent).
 */
/** @deprecated import from mobile-layout.ts — kept for existing tests. */
export function dockLayoutStyle(isExpanded: boolean): CSSProperties {
  return resolveDockLayoutStyle(isExpanded, false);
}

/** 15px stroke glyph at 1.7 — the v2 rail weight. */
export function WorkbenchIcon({ path }: { path: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={15}
      height={15}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.7}
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d={path} />
    </svg>
  );
}

/**
 * The rail bubble, in every state it can actually be in. 34px circle, 15px
 * glyph at 1.7 stroke.
 *
 *   rest        ink 90%, t3 glyph, line-14 edge, rail shadow
 *   open        blue fill, near-black glyph, blue edge, the blue lift
 *   coming      transparent fill, t6 glyph, half opacity
 *
 * NEVER a count badge, NEVER a red dot, NEVER a scale transform on hover.
 * Hover is a tint only and lives on `.ss-bubble` in pe-tokens.css so it works
 * without a JS hover handler.
 */
function bubbleStyle(active: boolean, coming: boolean): CSSProperties {
  return {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    padding: 0,
    width: PE.bubble,
    height: PE.bubble,
    borderRadius: "50%",
    cursor: "pointer",
    color: active ? "#08111F" : coming ? PE.t6 : PE.t3,
    background: active ? PE.blue : coming ? "transparent" : PE.bubbleRest,
    border: `1px solid ${active ? PE.blue : PE.line14}`,
    boxShadow: active ? PE.shOpen : PE.shRail,
    opacity: coming ? 0.5 : 1,
    transition: `background ${MOTION.state}, color ${MOTION.state}, border-color ${MOTION.state}, box-shadow ${MOTION.move}`,
  };
}

export interface WorkbenchProps {
  /** The tool registry (registry.tsx). Order = cluster order, top to bottom. */
  tools: WorkbenchToolDef[];
  /** The single open tool (null → dock closed). Owned by the app shell. */
  openToolId: string | null;
  onOpenToolChange: (next: string | null) => void;
  /**
   * Ignored for workbench tools. Kept so a caller cannot revive left
   * multi-open by passing an array — nextOpenToolId is the only rule.
   */
  openToolIds?: string[];
  onOpenToolIdsChange?: (next: string[]) => void;
  /** Always "right" for workbench docks. Default is right. */
  dockSide?: "left" | "right";
  /** Inspect card rendered inside the brief dock (desktop, right rail). */
  inspectSlot?: ReactNode;
  /** Active property = inspected parcel's node id, else the subject's. */
  activeParcelNodeId: string | null;
  host: WorkbenchHostActions;
  /** Injectable for tests; defaults to the app-wide singleton store. */
  store?: WorkbenchToolStateStore;
  /**
   * Seeds the dock stack. TEST SEAM, mirroring `store` above: this repo runs
   * vitest in a node environment with no click harness, so the only way to
   * prove the chassis RENDERS a stack (as opposed to proving the rules in
   * dock-stack.ts, which is a separate thing) is to hand it one. Production
   * never passes it; the stack builds from taps.
   */
  initialOpenIds?: string[];
  /** Surfaces that need the chassis context (inspect-card brief). */
  children?: ReactNode;
}

/**
 * The chassis surface: bubble cluster (always on) + the one shared dock
 * (rendered only while a tool is open). Mount ONCE in ExplorerMap.
 */
export function Workbench({
  tools,
  openToolId,
  onOpenToolChange,
  openToolIds: _ignoredOpenToolIds,
  onOpenToolIdsChange: _ignoredOnOpenToolIdsChange,
  dockSide = DEFAULT_DOCK_SIDE,
  inspectSlot,
  activeParcelNodeId,
  host,
  store,
  initialOpenIds,
  children,
}: WorkbenchProps) {
  const { isMobile, activeSheet, openSheet } = useMobilePanel();
  const mobileResearchOpen = isMobile && activeSheet === "research";
  const railTools = tools.filter((t) => t.inCluster !== false);
  void _ignoredOpenToolIds;
  void _ignoredOnOpenToolIdsChange;
  void dockSide;

  // THE STACK. The shell still owns ONE `openToolId` — that is the expanded
  // tool — and this chassis owns which other tools are open behind it. Keeping
  // the shell's prop shape unchanged is what let stacking land without
  // rewriting ExplorerMap's state or its ensureWorkbenchTool callers.
  const [stack, setStack] = useState<DockStack>(() =>
    initialOpenIds && initialOpenIds.length > 0
      ? {
          open: initialOpenIds,
          expanded: openToolId ?? initialOpenIds[initialOpenIds.length - 1],
        }
      : EMPTY_STACK,
  );
  const known = useMemo(() => new Set(tools.map((t) => t.id)), [tools]);

  // Reconcile in render, not in an effect: an effect would paint one frame of
  // the wrong stack every time the shell opens a tool (ensureWorkbenchTool on
  // a parcel click), which reads as a flicker.
  const synced = pruneStack(syncStack(stack, openToolId), known);
  if (synced !== stack) {
    // Same-render state catch-up. Legal, and cheaper than the extra paint.
    setStack(synced);
  }

  // Mobile keeps ONE sheet: stacking is a desktop-column behaviour and a
  // stack of folded headers on a phone is worse than a single sheet.
  const stackedIds = isMobile
    ? synced.expanded
      ? [synced.expanded]
      : []
    : synced.open;
  const openIds = synced.open;
  const openTool = synced.expanded
    ? (tools.find((t) => t.id === synced.expanded) ?? null)
    : null;

  const applyStack = (next: DockStack) => {
    setStack(next);
    if (next.expanded !== openToolId) onOpenToolChange(next.expanded);
  };
  const tapBubble = (id: string) => applyStack(tapDock(synced, id));
  const expandOne = (id: string) => applyStack(expandDock(synced, id));
  const closeOne = (id: string) => applyStack(closeOneDock(synced, id));
  // The dock-level close a TOOL calls through WorkbenchContext closes the tool
  // that is expanded, not the whole column.
  const closeDock = () => {
    if (synced.expanded) applyStack(closeOneDock(synced, synced.expanded));
    else onOpenToolChange(null);
  };

  // EXPAND-TO-FLOATING-BOX (general pattern for every right-side report/tool):
  // the dock can enlarge to a large floating box that keeps the map visible
  // around it — NOT full-screen — so cramped report content (the flood study
  // map thumbnail + legend especially) becomes clearly readable. Expand state
  // is transient: it resets whenever the open tool changes or the dock closes
  // (a fresh tool always opens at the compact size). Only tools that opt in
  // (`expandable`, default true) show the control.
  const [expanded, setExpanded] = useState(false);
  useEffect(() => {
    // Reset on tool switch / close — never carry an expanded box into the
    // next tool or a closed dock.
    setExpanded(false);
  }, [openToolId]);
  const canExpand = openTool ? openTool.expandable !== false : false;
  const isExpanded = expanded && canExpand;

  return (
    <WorkbenchProvider
      activeParcelNodeId={activeParcelNodeId}
      closeDock={closeDock}
      host={host}
      store={store}
    >
      {children}
      {/* THE BUBBLE CLUSTER — the only always-on workbench element. Pushed
          DOWN below the MapLibre zoom/compass NavigationControl (added
          top-right in map-renderer.js): the control stack is ~10px margin +
          three ~29px buttons ≈ 100px, so the cluster starts at top:118 to
          clear it and the two upper-right chrome elements no longer overlap.
          zIndex raised 9 → 11 so these SMALL bubbles sit in front of the large
          right-side dock (zIndex 9) per the small-in-front-of-large rule. */}
      <div
        data-testid="workbench-cluster"
        style={workbenchClusterStyle(isMobile)}
      >
        {railTools.map((tool) => {
          const active = openIds.includes(tool.id);
          return (
            <BubbleTip
              key={tool.id}
              side="left"
              label={tool.label}
              detail={
                tool.status === "coming"
                  ? "Coming soon"
                  : tool.tip
              }
            >
              <button
                type="button"
                className="ss-bubble pe-btn"
                data-open={active ? "1" : undefined}
                data-coming={tool.status === "coming" ? "1" : undefined}
                data-testid={`workbench-bubble-${tool.id}`}
                aria-label={tool.label}
                aria-pressed={active}
                onClick={() => tapBubble(tool.id)}
                style={bubbleStyle(active, tool.status === "coming")}
              >
                {tool.icon}
              </button>
            </BubbleTip>
          );
        })}
      </div>

      {/* Mobile research sheet — horizontal tool picker (replaces top-right cluster). */}
      {isMobile && mobileResearchOpen && !isExpanded && (
        <div
          data-testid="workbench-mobile-picker"
          style={mobileToolPickerStyle()}
        >
          {railTools.map((tool) => {
            const active = openIds.includes(tool.id);
            return (
              <button
                key={tool.id}
                type="button"
                className="ss-bubble pe-btn"
                data-open={active ? "1" : undefined}
                data-coming={tool.status === "coming" ? "1" : undefined}
                data-testid={`workbench-mobile-bubble-${tool.id}`}
                aria-label={tool.label}
                aria-pressed={active}
                onClick={() => {
                  openSheet("research");
                  tapBubble(tool.id);
                }}
                style={{
                  ...bubbleStyle(active, tool.status === "coming"),
                  flexShrink: 0,
                }}
              >
                {tool.icon}
              </button>
            );
          })}
        </div>
      )}

      {/* THE DOCK COLUMN. Every open tool lives here, oldest at the top. The
          newest is expanded; the rest fold to their 36px header and stay one
          click away. Nothing is closed on the user's behalf.

          The expand-to-floating-box case leaves the column entirely: that tool
          becomes the large readable box while the others stay stacked behind
          it, so a flood study can be read full-size without losing the chat
          you had open beside it. */}
      {stackedIds.length > 0 && (!isMobile || mobileResearchOpen) && (
        <div
          data-testid="workbench-dock-column"
          data-count={stackedIds.length}
          style={
            isMobile
              ? {
                  position: "fixed",
                  zIndex: 15,
                  ...resolveDockLayoutStyle(false, true),
                }
              : {
                  position: "absolute",
                  zIndex: 9,
                  top: 12,
                  right: 54,
                  width: "min(340px, calc(100vw - 78px))",
                  maxHeight: "calc(100vh - 28px)",
                  display: "flex",
                  flexDirection: "column",
                  gap: 8,
                  overflowY: "auto",
                  pointerEvents: "none",
                }
          }
        >
          {stackedIds.map((id) => {
            const tool = tools.find((t) => t.id === id);
            if (!tool) return null;
            const isOpen = id === synced.expanded;
            const boxed = isOpen && isExpanded;
            const foldable = !isMobile && stackedIds.length > 1;
            return (
              <section
                key={id}
                data-testid="workbench-dock"
                data-tool={tool.id}
                data-dock-side={DEFAULT_DOCK_SIDE}
                data-folded={!isOpen ? "1" : undefined}
                data-expanded={boxed ? "1" : undefined}
                data-mobile-dock={isMobile ? "1" : undefined}
                data-ss-motion=""
                style={{
                  pointerEvents: "auto",
                  flex: "0 0 auto",
                  boxShadow: PE.shDock,
                  ...(boxed
                    ? {
                        position: "fixed",
                        zIndex: 12,
                        ...resolveDockLayoutStyle(true, isMobile),
                      }
                    : null),
                  display: "flex",
                  flexDirection: "column",
                  overflow: "hidden",
                  borderRadius: isMobile ? undefined : PE.rFloat,
                  color: PE.t3,
                  background: PE.panel,
                  border: isMobile ? "none" : `1px solid ${PE.line14}`,
                  borderTop: isMobile ? `1px solid ${PE.line14}` : undefined,
                  font: `12.5px/1.5 ${PE.ui}`,
                  // The one panel motion: a dock opens its own height while
                  // scaling up 3% from the corner it hangs off. It never
                  // slides in from off-screen and never overshoots.
                  transformOrigin: isMobile ? "bottom center" : "right top",
                  animation: `pe-dock-in ${PE.dMove} ${PE.ease} both`,
                }}
              >
                {/* HEADER — pinned, and the whole hit target when folded. */}
                <div
                  data-testid="dock-header"
                  role={foldable && !isOpen ? "button" : undefined}
                  tabIndex={foldable && !isOpen ? 0 : undefined}
                  aria-expanded={foldable ? isOpen : undefined}
                  onClick={foldable && !isOpen ? () => expandOne(id) : undefined}
                  onKeyDown={
                    foldable && !isOpen
                      ? (e) => {
                          if (e.key === "Enter" || e.key === " ") {
                            e.preventDefault();
                            expandOne(id);
                          }
                        }
                      : undefined
                  }
                  style={{
                    flex: "0 0 auto",
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    height: PE.hHead,
                    padding: "0 8px 0 12px",
                    cursor: foldable && !isOpen ? "pointer" : undefined,
                    // A folded header drops its fill and its bottom rule and
                    // dims its glyph and title one step. That is the whole
                    // difference; it never becomes a different component.
                    borderBottom: `1px solid ${isOpen ? PE.line06 : "transparent"}`,
                    background: isOpen ? "rgba(255,255,255,.015)" : "transparent",
                    transition: `background ${MOTION.state}, border-color ${MOTION.state}`,
                  }}
                >
                  <span
                    aria-hidden
                    className="ss-dock-glyph"
                    style={{
                      display: "inline-flex",
                      flex: "none",
                      color: isOpen ? PE.blue : PE.t5,
                      transition: `color ${MOTION.state}`,
                    }}
                  >
                    {tool.icon}
                  </span>
                  <span
                    style={{
                      flex: 1,
                      minWidth: 0,
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: ".1em",
                      textTransform: "uppercase",
                      color: isOpen ? PE.t3 : PE.t5,
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                      transition: `color ${MOTION.state}`,
                    }}
                  >
                    {tool.label}
                  </span>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                    {foldable && (
                      <svg
                        viewBox="0 0 24 24"
                        width={12}
                        height={12}
                        aria-hidden
                        fill="none"
                        stroke={PE.t5}
                        strokeWidth={1.7}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        data-ss-motion=""
                        style={{
                          flex: "none",
                          transform: isOpen ? "rotate(0deg)" : "rotate(-90deg)",
                          transition: `transform ${MOTION.move}`,
                        }}
                      >
                        <path d="m6 9 6 6 6-6" />
                      </svg>
                    )}
                    {isOpen && canExpand && (
                      <button
                        type="button"
                        aria-label={isExpanded ? "Collapse report" : "Expand report"}
                        aria-pressed={isExpanded}
                        title={
                          isExpanded
                            ? "Collapse to the compact panel"
                            : "Expand to a large readable view (map stays visible)"
                        }
                        data-testid="dock-expand"
                        className="ss-headbtn pe-btn"
                        onClick={(e) => {
                          e.stopPropagation();
                          setExpanded((v) => !v);
                        }}
                        style={{
                          display: "inline-flex",
                          alignItems: "center",
                          justifyContent: "center",
                          width: 22,
                          height: 22,
                          borderRadius: 6,
                          background: "transparent",
                          border: "none",
                          color: PE.t5,
                          cursor: "pointer",
                          padding: 0,
                          lineHeight: 1,
                        }}
                      >
                        <svg
                          viewBox="0 0 24 24"
                          width={13}
                          height={13}
                          aria-hidden="true"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth={1.7}
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          {isExpanded ? (
                            <path d="M15 9h4m0 0V5m0 4-5-5M9 15H5m0 0v4m0-4 5 5" />
                          ) : (
                            <path d="M15 3h6m0 0v6m0-6-7 7M9 21H3m0 0v-6m0 6 7-7" />
                          )}
                        </svg>
                      </button>
                    )}
                    {/* The close control is SEPARATE from the header hit
                        target and must stopPropagation, or closing a folded
                        dock would expand it on the way out. */}
                    <button
                      type="button"
                      aria-label="Close"
                      data-testid="dock-close"
                      className="ss-headbtn pe-btn"
                      onClick={(e) => {
                        e.stopPropagation();
                        closeOne(id);
                      }}
                      style={{
                        display: "inline-flex",
                        alignItems: "center",
                        justifyContent: "center",
                        width: 22,
                        height: 22,
                        borderRadius: 6,
                        background: "transparent",
                        border: "none",
                        color: PE.t5,
                        cursor: "pointer",
                        lineHeight: 1,
                        padding: 0,
                      }}
                    >
                      <svg
                        viewBox="0 0 24 24"
                        width={13}
                        height={13}
                        aria-hidden="true"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth={1.7}
                        strokeLinecap="round"
                      >
                        <path d="M18 6 6 18 M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                </div>

                {/* THE FOLD. The body animates its own height to zero and
                    back; the dock height follows it. 220ms of height and
                    140ms of opacity, on the one curve. */}
                <div
                  data-ss-motion=""
                  style={{
                    flex: "1 1 auto",
                    minHeight: 0,
                    maxHeight: isOpen
                      ? boxed
                        ? "none"
                        : "calc(100vh - 128px)"
                      : 0,
                    opacity: isOpen ? 1 : 0,
                    overflow: "hidden",
                    transition: `max-height ${MOTION.open}, opacity ${MOTION.state}`,
                  }}
                >
                  <div
                    className="pe-dock-scroll"
                    data-testid="dock-scroll"
                    style={{
                      height: "100%",
                      overflowY: "auto",
                      WebkitOverflowScrolling: "touch",
                      padding: "14px 13px",
                    }}
                  >
                    <DockBody
                      tool={tool}
                      activeParcelNodeId={activeParcelNodeId}
                      closeDock={closeDock}
                      host={host}
                      prefix={tool.id === "brief" ? inspectSlot : null}
                    />
                  </div>
                </div>
              </section>
            );
          })}
        </div>
      )}
    </WorkbenchProvider>
  );
}

/** The dock's honest-state gate, then the tool's own content. */
function DockBody({
  tool,
  activeParcelNodeId,
  closeDock,
  host,
  prefix = null,
}: {
  tool: WorkbenchToolDef;
  activeParcelNodeId: string | null;
  closeDock: () => void;
  host: WorkbenchHostActions;
  prefix?: ReactNode;
}): ReactNode {
  // Registered-but-not-live: an HONEST coming state — never dead-looking UI.
  // Both branches below name WHAT IS MISSING AND WHAT WOULD FILL IT, which is
  // the whole contract of the honest-empty register.
  if (tool.status === "coming" || !tool.render) {
    return (
      <StateNote
        data-testid="dock-coming"
        register="nothing-yet"
        title={`${tool.label} is not wired up yet`}
        basis={
          <>
            It is registered on the workbench so the rail stays honest about
            what is coming, but nothing here is live. It arrives in a later
            build wave.
          </>
        }
      />
    );
  }
  // Property-scoped tool with no active property: honest, actionable state.
  if (tool.propertyScoped && !activeParcelNodeId) {
    return (
      <StateNote
        data-testid="dock-no-property"
        register="waiting"
        title="Select a property first"
        basis={
          <>
            Click a parcel on the map, or search an address or parcel id, and
            {" "}
            {tool.label.toLowerCase()} will scope to it.
          </>
        }
      />
    );
  }
  return (
    <>
      {prefix}
      {tool.render({ activeParcelNodeId, closeDock, host })}
    </>
  );
}
