import { useEffect, useState } from "react";
import {
  listSavedProperties,
  subscribeSavedPropertiesChanged,
} from "./savedPropertiesClient";
import { filedReportsFromSaved } from "../workbench/tools/reports-dossier";
import {
  loadSeen,
  markAllSeen,
  resolveSeen,
  saveSeen,
  subscribeReportsSeenChanged,
  unseenCount,
  notifyReportsSeenChanged,
} from "../workbench/tools/reports-seen";

// THE RAIL'S OTHER UNREAD SIGNAL.
//
// useRecordsUnread answers "do I have finished records-request jobs waiting".
// That is a narrow, specific thing — it says nothing about a Flood &
// Drainage study, an X-ray, or a Feasibility Study finishing, which is the
// deliverable a Studio/Solo subscriber generates constantly. Those are
// FILED REPORTS, tracked by reports-seen.ts (the same module that already
// drives the amber "not opened yet" pip in the My Reports library). This
// hook asks that module the same question at the toolbar level, before the
// Reports tool is ever opened.
//
// SAME DATA, NOT A SECOND OPINION. `filedReportsFromSaved` over
// `listSavedProperties()` is the exact derivation ReportsTool.tsx's
// ReportsLibrary uses to build the list it renders. This hook calls both
// independently (there is no shared cache — same as records-request's own
// inbox fetch), but because it is the same account, the same server route,
// and the same flattening function, it cannot disagree in substance with
// what the panel shows once it loads. A hook that invented its own idea of
// "filed" (e.g. a separate count endpoint) is exactly the mismatch that
// would make the dot lie.
//
// FAIL CLOSED, same rule as useRecordsUnread: signed out, an error, or an
// unreachable network all resolve to zero, and zero renders no dot. A dot
// lit by a failed fetch would be worse than none.
//
// NO POLLING. useRecordsUnread's 60s poll exists to catch async job
// completion server-side. Every report kind this hook covers (X-ray,
// Flood & Drainage, Feasibility Study, site-plan, terrain) is generated by
// an AWAITED request in this same tab, and filing it already calls
// `notifySavedPropertiesChanged()` (via attachExportToDossier ->
// updatePropertyDossier -> saveProperty) — the same signal
// ReportsTool.tsx's own library already subscribes to for live updates.
// Subscribing to that signal here, rather than adding a second poll loop,
// gets the same "learns about it without reopening the tool" result without
// repeating the 2026-08-28 records/inbox 429 incident (see
// useRecordsUnread.ts) on a second endpoint.

async function readFiledRows() {
  const outcome = await listSavedProperties();
  if (outcome.kind !== "ready") return null;
  return filedReportsFromSaved(outcome.items);
}

/**
 * The count for the rail. Reads once on mount, then again whenever a saved
 * property changes (a report was just filed) or the reports-seen store
 * changes (the tool was just opened and marked everything seen).
 */
export function useReportsUnread(): number {
  const [count, setCount] = useState(0);

  useEffect(() => {
    let cancelled = false;

    const read = () => {
      void readFiledRows()
        .then((filed) => {
          if (cancelled) return;
          // sign-in / error / unreachable: unknown, not "zero and lit".
          // Treated exactly like useRecordsUnread's `wired: false` — zero,
          // and stays zero until a read actually succeeds.
          if (filed === null) {
            setCount(0);
            return;
          }
          const seen = resolveSeen(filed, loadSeen());
          saveSeen(seen);
          setCount(unseenCount(filed, seen));
        })
        .catch(() => {
          // A failed read is not news. Never light the dot on an error.
          if (!cancelled) setCount(0);
        });
    };

    read();
    const unsubscribeSaved = subscribeSavedPropertiesChanged(read);
    // Re-read the instant the dock marks reports seen, so the dot goes out
    // when you look rather than waiting on the next saved-property write.
    const unsubscribeSeen = subscribeReportsSeenChanged(read);

    return () => {
      cancelled = true;
      unsubscribeSaved();
      unsubscribeSeen();
    };
  }, []);

  return count;
}

/**
 * Opening the Reports tool marks every currently filed report as seen and
 * darkens the dot — the reports-side equivalent of markRecordsSeenNow. The
 * dot goes out because you opened the tool, not because time passed.
 */
export async function markReportsSeenNow(): Promise<void> {
  try {
    const filed = await readFiledRows();
    if (filed === null) return;
    const seen = resolveSeen(filed, loadSeen());
    saveSeen(markAllSeen(filed, seen));
    notifyReportsSeenChanged();
  } catch {
    // Failing to remember that you looked is not worth an error path.
  }
}
